#!/bin/sh
. .travis/common.sh

if [ -d debian ]; then
    echo "Debian build failed"
else
    if [ ! x${DIST} = x ]; then
	echo "skipping this build"
	exit 0
    fi

    # Dump as much log as we can
    find $build_dir -name "*.log" | xargs cat
fi
