#!/bin/sh
set -e

# Directories.
root_dir=`pwd`

if [ -d debian ]; then
    build_dir="/tmp/_travis/build"
    install_dir="/tmp/_travis/install"
else
    build_dir="$root_dir/_travis/build"
    install_dir="$root_dir/_travis/install"
fi


if [ -d debian ]; then
    echo "Debian build failed"
else
    if [ ! x${DIST} = x ]; then
	echo "skipping this build"
	exit 0
    fi

    # Dump as much log as we can
    find $build_dir -name "*.log" | xargs cat
fi
