#!/bin/bash
. `dirname $0`/../common.sh

# If the ros version is not defined, quit.
if `test x${ROS_DISTRO} = x`; then
  exit 0
fi

${SUDO_CMD} sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -c -s` main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | ${SUDO_CMD} apt-key add -
${SUDO_CMD} apt-get update

if `test x${ROS_DISTRO} = xjade`; then
  ${SUDO_CMD} apt-get install ros-jade-ros-base ros-jade-rosdoc-lite python-catkin-lint
elif `test x${ROS_DISTRO} = xindigo`; then
  ${SUDO_CMD} apt-get install ros-indigo-ros-base ros-indigo-rosdoc-lite python-catkin-lint
elif `test x${ROS_DISTRO} = xhydro`; then
  ${SUDO_CMD} apt-get install ros-hydro-ros-base ros-hydro-rosdoc-lite python-catkin-lint
elif `test x${ROS_DISTRO} = xgroovy`; then
  ${SUDO_CMD} apt-get install ros-groovy-ros-base ros-groovy-rosdoc-lite python-catkin-lint
else
  echo "ROS distribution unkown, exiting" + ${ROS_DISTRO}
  exit 1
fi
. /opt/ros/${ROS_DISTRO}/setup.sh

# workspace
CATKIN_WORKSPACE=$build_dir/..
ln -s $root_dir/.. $CATKIN_WORKSPACE/src
cd $CATKIN_WORKSPACE/src
catkin_init_workspace

